/**
 * rl_agent.ts — Browser-side inference for the trained PPO tennis agent.
 *
 * Auto-generated by export_model.py. Do not edit manually.
 *
 * Usage in useGameState.ts:
 *   import { initRLAgent, rlAgentShot } from './rl_agent';
 *
 *   // Call once on app init:
 *   await initRLAgent();
 *
 *   // Replace generateAiShot(...):
 *   const nextShot = rlAgentShot(newAiPos, state.playerPos, gameState);
 */

import { Vec2, Shot, Difficulty, PlayStyle } from '../types';
import { COURT } from './court';
import { computeVz } from './kinematics';

// ── Types ─────────────────────────────────────────────────────────────────────

interface LayerWeights {
  type: string;
  W: number[][];
  b: number[];
  ln_weight?: number[];
  ln_bias?: number[];
  ln_eps?: number;
}

interface ModelWeights {
  obs_dim: number;
  act_dim: number;
  court: { width: number; net_y: number; margin: number; net_margin: number };
  layers: LayerWeights[];
  actor_log_std?: number[];
}

// ── Shot config ───────────────────────────────────────────────────────────────

export interface RLShotConfig {
  speed: number;         // ball speed m/s
  minTravelTime: number; // minimum flight time (reaction window)
  blendToPlayer: number; // 0 = raw RL output, 1 = always aim at player
  xMargin: number;       // keep shots this far from sidelines
  nearY: number;         // minimum landing depth from player baseline
  netBuffer: number;     // keep shots this far from net
}

const BASE_CONFIGS: Record<Difficulty, RLShotConfig> = {
  easy:   { speed: 6.5,  minTravelTime: 2.4,  blendToPlayer: 0.55, xMargin: 1.5,  nearY: 2.2, netBuffer: 2.0 },
  medium: { speed: 8.5,  minTravelTime: 1.6,  blendToPlayer: 0.35, xMargin: 0.9,  nearY: 2.2, netBuffer: 2.0 },
  hard:   { speed: 10.5, minTravelTime: 1.0,  blendToPlayer: 0.10, xMargin: 0.4,  nearY: 2.2, netBuffer: 2.0 },
  expert: { speed: 13.0, minTravelTime: 0.65, blendToPlayer: 0.0,  xMargin: 0.15, nearY: 1.5, netBuffer: 2.0 },
};

const STYLE_DELTAS: Record<PlayStyle, { speed: number; time: number; blend: number; nearY: number }> = {
  aggressive: { speed:  1.5, time: -0.25, blend: -0.20, nearY: 1.5 },
  balanced:   { speed:  0.0, time:  0.0,  blend:  0.0,  nearY: 2.2 },
  consistent: { speed: -1.0, time:  0.4,  blend:  0.15, nearY: 4.5 },
};

export function buildRLConfig(difficulty: Difficulty, style: PlayStyle): RLShotConfig {
  const base  = BASE_CONFIGS[difficulty];
  const delta = STYLE_DELTAS[style];
  return {
    speed:         Math.max(5.0, base.speed + delta.speed),
    minTravelTime: Math.max(0.5, base.minTravelTime + delta.time),
    blendToPlayer: Math.max(0.0, Math.min(0.8, base.blendToPlayer + delta.blend)),
    xMargin:       base.xMargin,
    nearY:         delta.nearY,
    netBuffer:     base.netBuffer,
  };
}

const DEFAULT_CONFIG: RLShotConfig = buildRLConfig('medium', 'balanced');

// ── Module state ──────────────────────────────────────────────────────────────

let _weights: ModelWeights | null = null;
const N_FRAMES = 3;
const N_FEATURES = 8;
const STOCHASTIC_POLICY_TEMPERATURE = 0.75;
const STOCHASTIC_MEAN_CLAMP = 0.95;
// Ring buffer for frame stacking
const _frameBuffer: number[][] = [];

// ── Init ──────────────────────────────────────────────────────────────────────

export async function initRLAgent(weightsUrl = '/rl_weights.json'): Promise<void> {
  const res = await fetch(weightsUrl);
  _weights = (await res.json()) as ModelWeights;
  _frameBuffer.length = 0;
  console.log('[RL Agent] Weights loaded.');
}

// ── Forward pass ──────────────────────────────────────────────────────────────

function matVec(W: number[][], x: number[]): number[] {
  return W.map(row => row.reduce((s, w, j) => s + w * x[j], 0));
}

function addBias(x: number[], b: number[]): number[] {
  return x.map((v, i) => v + b[i]);
}

function tanh(x: number[]): number[] {
  return x.map(v => Math.tanh(v));
}

function layerNorm(x: number[], w: number[], b: number[], eps: number): number[] {
  const mean = x.reduce((s, v) => s + v, 0) / x.length;
  const variance = x.reduce((s, v) => s + (v - mean) ** 2, 0) / x.length;
  const std = Math.sqrt(variance + eps);
  return x.map((v, i) => w[i] * ((v - mean) / std) + b[i]);
}

function forward(obs: number[]): number[] {
  if (!_weights) throw new Error('RL Agent not initialised — call initRLAgent() first.');
  let h = obs;
  for (const layer of _weights.layers) {
    h = addBias(matVec(layer.W, h), layer.b);
    if (layer.ln_weight && layer.ln_bias && layer.ln_eps !== undefined) {
      h = layerNorm(h, layer.ln_weight, layer.ln_bias, layer.ln_eps);
    }
    if (layer.type === 'linear_layernorm_tanh' || layer.type === 'linear_tanh') {
      h = tanh(h);
    }
  }
  return h; // [action_0, action_1] ∈ [-1, 1]
}

function randn(): number {
  let u = 0;
  let v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function sampleTanhNormal(meanAction: number[]): number[] {
  if (!_weights?.actor_log_std) return meanAction;
  return meanAction.map((mean, i) => {
    const clippedMean = Math.max(-STOCHASTIC_MEAN_CLAMP, Math.min(STOCHASTIC_MEAN_CLAMP, mean));
    const preTanhMean = 0.5 * Math.log((1 + clippedMean) / (1 - clippedMean));
    const std = Math.exp(_weights!.actor_log_std![i] ?? -2) * STOCHASTIC_POLICY_TEMPERATURE;
    return Math.tanh(preTanhMean + randn() * std);
  });
}

// ── Observation builder ───────────────────────────────────────────────────────

function normX(x: number): number { return x / (COURT.widthM / 2) - 1; }
function normY(y: number): number { return y / (COURT.lengthM / 2) - 1; }
function normV(v: number): number { return Math.max(-1, Math.min(1, v / 6)); }

function buildFrame(
  aiPos: Vec2, aiVel: Vec2,
  playerPos: Vec2,
  lastBall: Vec2,
): number[] {
  // y-flip: AI sees court from its own perspective (baseline = y=0 in obs)
  const aiYFlip      = COURT.lengthM - aiPos.y;
  const oppYFlip     = COURT.lengthM - playerPos.y;
  const ballYFlip    = COURT.lengthM - lastBall.y;
  return [
    normX(aiPos.x),    normY(aiYFlip),
    normV(aiVel.x),    normV(-aiVel.y),
    normX(playerPos.x), normY(oppYFlip),
    normX(lastBall.x), normY(ballYFlip),
  ];
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Call this once per new point (when the point resets) to clear frame history.
 */
export function resetRLFrameBuffer(): void {
  _frameBuffer.length = 0;
}

/**
 * Replaces generateAiShot(). Returns a Shot for the AI to play.
 *
 * Parameters match what's available in the PLAYER_SHOT_LANDED branch of
 * the reducer in useGameState.ts.
 */
export function rlAgentShot(
  aiPos:     Vec2,
  playerPos: Vec2,
  lastBall:  Vec2,
  config:    RLShotConfig = DEFAULT_CONFIG,
  aiVel:     Vec2 = { x: 0, y: 0 },
): Shot {
  if (!_weights) {
    throw new Error('RL Agent not initialised — call initRLAgent() first.');
  }

  const frame = buildFrame(aiPos, aiVel, playerPos, lastBall);

  // Maintain rolling frame buffer (most-recent 3 frames)
  _frameBuffer.push(frame);
  if (_frameBuffer.length > N_FRAMES) _frameBuffer.shift();

  // Zero-pad if we don't have 3 frames yet (start of episode)
  const padded: number[][] = [];
  for (let i = 0; i < N_FRAMES; i++) {
    padded.push(_frameBuffer[_frameBuffer.length - N_FRAMES + i] ?? new Array(N_FEATURES).fill(0));
  }
  const obs = padded.flat();   // length 24

  const meanAction = forward(obs);   // [ax, ay] ∈ [-1, 1]
  const action = sampleTanhNormal(meanAction);

  // Map action → court landing coordinate (AI shoots toward player's half)
  // y-range matches training: [margin, net_y - net_margin] (NET_MARGIN buffer from net)
  const { margin, net_y, width, net_margin } = _weights.court;
  const landX = margin + ((action[0] + 1) / 2) * (width - 2 * margin);
  const landY = margin + ((action[1] + 1) / 2) * (net_y - net_margin - margin);

  const blendedX = landX * (1 - config.blendToPlayer) + playerPos.x * config.blendToPlayer;
  const blendedY = landY * (1 - config.blendToPlayer) + playerPos.y * config.blendToPlayer;

  const landing: Vec2 = {
    x: Math.max(config.xMargin, Math.min(width - config.xMargin, blendedX)),
    y: Math.max(config.nearY,   Math.min(net_y - config.netBuffer, blendedY)),
  };

  const dx = landing.x - aiPos.x;
  const dy = landing.y - aiPos.y;
  const dist = Math.sqrt(dx * dx + dy * dy);
  const travelTime = Math.max(dist / config.speed, config.minTravelTime);

  return {
    origin:     aiPos,
    landing,
    speed:      config.speed,
    spinType:   'flat',
    travelTime,
    vz:         computeVz(travelTime),
  };
}
